/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for tpm2key
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder tpm2key_decoder;

extern int tpm2_key_parent(void *, size_t, unsigned char, const void *, size_t);
extern int tpm2_key_priv(void *, size_t, unsigned char, const void *, size_t);
extern int tpm2_key_pub(void *, size_t, unsigned char, const void *, size_t);
extern int tpm2_key_type(void *, size_t, unsigned char, const void *, size_t);

